In [1]:
import pandas as pd

In [43]:
#maintain timestamps in a set
timestamps = set()

In [69]:
#read data from parquet file, exclude the index column
par1 = pd.read_parquet('./full_dataset/home/ubuntu/quant/tick_data/final_lob_data/min30_all_labeled_sample/labeled_tick_data_1287.parquet')
#sort the data by timestamp
par1 = par1.sort_values(by='time')

In [70]:
par1

,time,CurVolume,AskPrice1,AskVolume1,BidPrice1,BidVolume1,AskPrice2,AskVolume2,BidPrice2,BidVolume2,...,TotalOfferQty,LastPrice,BuyPrice,SellPrice1,LogReturn1,SellPrice2,LogReturn2,SellPrice3,LogReturn3,SecurityID
0,2023-11-01 09:30:00,1791784,21.69,2569184.0,21.34,2961326.0,21.70,2545900.0,21.33,3778194.0,...,668944076,21.50,21.53,21.60,0.003246,21.48,-0.002325,21.48,-0.002325,1287
1,2023-11-01 10:00:00,829112,21.63,3427677.0,21.48,2209537.0,21.64,5196076.0,21.46,2874760.0,...,903056566,21.53,21.62,21.60,-0.000925,21.31,-0.014442,21.31,-0.014442,1287
2,2023-11-01 10:30:00,583645,21.65,3182716.0,21.47,2126869.0,21.66,5705780.0,21.46,2775762.0,...,930059536,21.62,21.61,21.52,-0.004173,21.37,-0.011168,21.37,-0.011168,1287
3,2023-11-01 11:00:00,531363,21.68,3940419.0,21.56,3890107.0,21.69,4960300.0,21.55,5279077.0,...,922888979,21.61,21.60,21.49,-0.005106,21.39,-0.009770,21.39,-0.009770,1287
4,2023-11-01 11:30:00,400,21.60,45000.0,21.59,132000.0,21.61,24000.0,21.58,958110.0,...,51449520,21.60,21.60,21.52,-0.003711,21.39,-0.009770,21.39,-0.009770,1287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,2023-12-29 12:30:00,0,20.82,273000.0,20.81,126000.0,20.83,24000.0,20.80,330000.0,...,47173260,20.81,20.79,NaN,NaN,NaN,NaN,NaN,NaN,1287
469,2023-12-29 13:00:00,316865,20.82,3259922.0,20.76,2929970.0,20.83,2797936.0,20.75,5562450.0,...,754176382,20.79,20.83,NaN,NaN,NaN,NaN,NaN,NaN,1287
470,2023-12-29 13:30:00,196200,20.85,5983060.0,20.78,2901575.0,20.86,6139600.0,20.77,3872525.0,...,731950634,20.83,20.83,NaN,NaN,NaN,NaN,NaN,NaN,1287
471,2023-12-29 14:00:00,280500,20.87,6487600.0,20.81,4695200.0,20.88,9914100.0,20.80,5873700.0,...,812239096,20.83,20.83,NaN,NaN,NaN,NaN,NaN,NaN,1287
472,2023-12-29 14:30:00,406923,20.85,9597872.0,20.80,6562698.0,20.86,12517680.0,20.79,8607996.0,...,752267602,20.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1287

In [71]:
#drop SellPrice1, LogReturn1, SellPrice2, SellPrice3, LogReturn3
par1 = par1.drop(columns=['SellPrice1', 'LogReturn1', 'SellPrice2', 'SellPrice3', 'LogReturn3'])
#read SecurityID and check if they are all the same
security_id = par1['SecurityID'].unique()
#drop SecurityID
par1 = par1.drop(columns=['SecurityID'])

In [72]:
par1

,time,CurVolume,AskPrice1,AskVolume1,BidPrice1,BidVolume1,AskPrice2,AskVolume2,BidPrice2,BidVolume2,TotalBidQty,TotalOfferQty,LastPrice,BuyPrice,LogReturn2
0,2023-11-01 09:30:00,1791784,21.69,2569184.0,21.34,2961326.0,21.70,2545900.0,21.33,3778194.0,225513802,668944076,21.50,21.53,-0.002325
1,2023-11-01 10:00:00,829112,21.63,3427677.0,21.48,2209537.0,21.64,5196076.0,21.46,2874760.0,343112993,903056566,21.53,21.62,-0.014442
2,2023-11-01 10:30:00,583645,21.65,3182716.0,21.47,2126869.0,21.66,5705780.0,21.46,2775762.0,322761107,930059536,21.62,21.61,-0.011168
3,2023-11-01 11:00:00,531363,21.68,3940419.0,21.56,3890107.0,21.69,4960300.0,21.55,5279077.0,360040889,922888979,21.61,21.60,-0.009770
4,2023-11-01 11:30:00,400,21.60,45000.0,21.59,132000.0,21.61,24000.0,21.58,958110.0,20630370,51449520,21.60,21.60,-0.009770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,2023-12-29 12:30:00,0,20.82,273000.0,20.81,126000.0,20.83,24000.0,20.80,330000.0,13218000,47173260,20.81,20.79,NaN
469,2023-12-29 13:00:00,316865,20.82,3259922.0,20.76,2929970.0,20.83,2797936.0,20.75,5562450.0,193560526,754176382,20.79,20.83,NaN
470,2023-12-29 13:30:00,196200,20.85,5983060.0,20.78,2901575.0,20.86,6139600.0,20.77,3872525.0,183188179,731950634,20.83,20.83,NaN
471,2023-12-29 14:00:00,280500,20.87,6487600.0,20.81,4695200.0,20.88,9914100.0,20.80,5873700.0,194861216,812239096,20.83,20.83,NaN
472,2023-12-29 14:30:00,406923,20.85,9597872.0,20.80,6562698.0,20.86,12517680.0,20.79,8607996.0,177493230,752267602,20.83,NaN,NaN

In [73]:
# #drop rows where LogReturn2 is NaN
# par1 = par1.dropna(subset=['LogReturn2'])

#fill nan in other columns (besides time) with last valid observation
par1 = par1.fillna(method='ffill')

,time,CurVolume,AskPrice1,AskVolume1,BidPrice1,BidVolume1,AskPrice2,AskVolume2,BidPrice2,BidVolume2,TotalBidQty,TotalOfferQty,LastPrice,BuyPrice,LogReturn2
0,2023-11-01 09:30:00,1791784,21.69,2569184.0,21.34,2961326.0,21.70,2545900.0,21.33,3778194.0,225513802,668944076,21.50,21.53,-0.002325
1,2023-11-01 10:00:00,829112,21.63,3427677.0,21.48,2209537.0,21.64,5196076.0,21.46,2874760.0,343112993,903056566,21.53,21.62,-0.014442
2,2023-11-01 10:30:00,583645,21.65,3182716.0,21.47,2126869.0,21.66,5705780.0,21.46,2775762.0,322761107,930059536,21.62,21.61,-0.011168
3,2023-11-01 11:00:00,531363,21.68,3940419.0,21.56,3890107.0,21.69,4960300.0,21.55,5279077.0,360040889,922888979,21.61,21.60,-0.009770
4,2023-11-01 11:30:00,400,21.60,45000.0,21.59,132000.0,21.61,24000.0,21.58,958110.0,20630370,51449520,21.60,21.60,-0.009770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,2023-12-29 12:30:00,0,20.82,273000.0,20.81,126000.0,20.83,24000.0,20.80,330000.0,13218000,47173260,20.81,20.79,-0.000480
469,2023-12-29 13:00:00,316865,20.82,3259922.0,20.76,2929970.0,20.83,2797936.0,20.75,5562450.0,193560526,754176382,20.79,20.83,-0.000480
470,2023-12-29 13:30:00,196200,20.85,5983060.0,20.78,2901575.0,20.86,6139600.0,20.77,3872525.0,183188179,731950634,20.83,20.83,-0.000480
471,2023-12-29 14:00:00,280500,20.87,6487600.0,20.81,4695200.0,20.88,9914100.0,20.80,5873700.0,194861216,812239096,20.83,20.83,-0.000480
472,2023-12-29 14:30:00,406923,20.85,9597872.0,20.80,6562698.0,20.86,12517680.0,20.79,8607996.0,177493230,752267602,20.83,20.83,-0.000480

In [57]:
timestamps.update(par1['time'])

In [58]:
len(timestamps)

462

In [59]:
#check if there are any NaN values left
nan_values = par1.isna().sum().sum()

In [60]:
nan_values

0

In [61]:
par1

,time,CurVolume,AskPrice1,AskVolume1,BidPrice1,BidVolume1,AskPrice2,AskVolume2,BidPrice2,BidVolume2,TotalBidQty,TotalOfferQty,LastPrice,BuyPrice,LogReturn2
0,2023-11-01 09:30:00,1791784,21.69,2569184.0,21.34,2961326.0,21.70,2545900.0,21.33,3778194.0,225513802,668944076,21.50,21.53,-0.002325
1,2023-11-01 10:00:00,829112,21.63,3427677.0,21.48,2209537.0,21.64,5196076.0,21.46,2874760.0,343112993,903056566,21.53,21.62,-0.014442
2,2023-11-01 10:30:00,583645,21.65,3182716.0,21.47,2126869.0,21.66,5705780.0,21.46,2775762.0,322761107,930059536,21.62,21.61,-0.011168
3,2023-11-01 11:00:00,531363,21.68,3940419.0,21.56,3890107.0,21.69,4960300.0,21.55,5279077.0,360040889,922888979,21.61,21.60,-0.009770
4,2023-11-01 11:30:00,400,21.60,45000.0,21.59,132000.0,21.61,24000.0,21.58,958110.0,20630370,51449520,21.60,21.60,-0.009770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,2023-12-28 12:30:00,0,20.61,456000.0,20.60,729000.0,20.62,204000.0,20.59,33000.0,13682520,29618520,20.60,20.65,0.007718
458,2023-12-28 13:00:00,471385,20.70,2767762.0,20.58,2990986.0,20.71,4039516.0,20.56,3683085.0,255494153,600314918,20.65,20.57,0.010638
459,2023-12-28 13:30:00,404300,20.68,4899814.0,20.57,10001140.0,20.69,4856030.0,20.56,5625160.0,254471025,647402117,20.57,20.57,0.012561
460,2023-12-28 14:00:00,305318,20.64,4559602.0,20.55,5146134.0,20.65,7760826.0,20.54,6638156.0,237449643,649014975,20.57,20.57,0.012561
461,2023-12-28 14:30:00,547582,20.58,5468404.0,20.51,7040337.0,20.59,7321706.0,20.50,10858701.0,225038234,700283029,20.57,20.84,-0.000480

In [62]:
#save the data to a new csv file
par1.to_csv('./30min_datasets/S1287.csv', index=False)

In [104]:
import numpy as np
times = np.load('./30min_datasets_full/timestamps.npy')

In [105]:
times

array(['2023-11-01T09:30:00.000000000', '2023-11-01T10:00:00.000000000',
       '2023-11-01T10:30:00.000000000', '2023-11-01T11:00:00.000000000',
       '2023-11-01T11:30:00.000000000', '2023-11-01T12:00:00.000000000',
       '2023-11-01T12:30:00.000000000', '2023-11-01T13:00:00.000000000',
       '2023-11-01T13:30:00.000000000', '2023-11-01T14:00:00.000000000',
       '2023-11-01T14:30:00.000000000', '2023-11-02T09:30:00.000000000',
       '2023-11-02T10:00:00.000000000', '2023-11-02T10:30:00.000000000',
       '2023-11-02T11:00:00.000000000', '2023-11-02T11:30:00.000000000',
       '2023-11-02T12:00:00.000000000', '2023-11-02T12:30:00.000000000',
       '2023-11-02T13:00:00.000000000', '2023-11-02T13:30:00.000000000',
       '2023-11-02T14:00:00.000000000', '2023-11-02T14:30:00.000000000',
       '2023-11-03T09:30:00.000000000', '2023-11-03T10:00:00.000000000',
       '2023-11-03T10:30:00.000000000', '2023-11-03T11:00:00.000000000',
       '2023-11-03T11:30:00.000000000', '2023-11-03T12:00:00.000000000',
       '2023-11-03T12:30:00.000000000', '2023-11-03T13:00:00.000000000',
       '2023-11-03T13:30:00.000000000', '2023-11-03T14:00:00.000000000',
       '2023-11-03T14:30:00.000000000', '2023-11-06T09:30:00.000000000',
       '2023-11-06T10:00:00.000000000', '2023-11-06T10:30:00.000000000',
       '2023-11-06T11:00:00.000000000', '2023-11-06T11:30:00.000000000',
       '2023-11-06T12:00:00.000000000', '2023-11-06T12:30:00.000000000',
       '2023-11-06T13:00:00.000000000', '2023-11-06T13:30:00.000000000',
       '2023-11-06T14:00:00.000000000', '2023-11-06T14:30:00.000000000',
       '2023-11-07T09:30:00.000000000', '2023-11-07T10:00:00.000000000',
       '2023-11-07T10:30:00.000000000', '2023-11-07T11:00:00.000000000',
       '2023-11-07T11:30:00.000000000', '2023-11-07T12:00:00.000000000',
       '2023-11-07T12:30:00.000000000', '2023-11-07T13:00:00.000000000',
       '2023-11-07T13:30:00.000000000', '2023-11-07T14:00:00.000000000',
       '2023-11-07T14:30:00.000000000', '2023-11-08T09:30:00.000000000',
       '2023-11-08T10:00:00.000000000', '2023-11-08T10:30:00.000000000',
       '2023-11-08T11:00:00.000000000', '2023-11-08T11:30:00.000000000',
       '2023-11-08T12:00:00.000000000', '2023-11-08T12:30:00.000000000',
       '2023-11-08T13:00:00.000000000', '2023-11-08T13:30:00.000000000',
       '2023-11-08T14:00:00.000000000', '2023-11-08T14:30:00.000000000',
       '2023-11-09T09:30:00.000000000', '2023-11-09T10:00:00.000000000',
       '2023-11-09T10:30:00.000000000', '2023-11-09T11:00:00.000000000',
       '2023-11-09T11:30:00.000000000', '2023-11-09T12:00:00.000000000',
       '2023-11-09T12:30:00.000000000', '2023-11-09T13:00:00.000000000',
       '2023-11-09T13:30:00.000000000', '2023-11-09T14:00:00.000000000',
       '2023-11-09T14:30:00.000000000', '2023-11-10T09:30:00.000000000',
       '2023-11-10T10:00:00.000000000', '2023-11-10T10:30:00.000000000',
       '2023-11-10T11:00:00.000000000', '2023-11-10T11:30:00.000000000',
       '2023-11-10T12:00:00.000000000', '2023-11-10T12:30:00.000000000',
       '2023-11-10T13:00:00.000000000', '2023-11-10T13:30:00.000000000',
       '2023-11-10T14:00:00.000000000', '2023-11-10T14:30:00.000000000',
       '2023-11-13T09:30:00.000000000', '2023-11-13T10:00:00.000000000',
       '2023-11-13T10:30:00.000000000', '2023-11-13T11:00:00.000000000',
       '2023-11-13T11:30:00.000000000', '2023-11-13T12:00:00.000000000',
       '2023-11-13T12:30:00.000000000', '2023-11-13T13:00:00.000000000',
       '2023-11-13T13:30:00.000000000', '2023-11-13T14:00:00.000000000',
       '2023-11-13T14:30:00.000000000', '2023-11-14T09:30:00.000000000',
       '2023-11-14T10:00:00.000000000', '2023-11-14T10:30:00.000000000',
       '2023-11-14T11:00:00.000000000', '2023-11-14T11:30:00.000000000',
       '2023-11-14T12:00:00.000000000', '2023-11-14T12:30:00.000000000',
       '2023-11-14T13:00:00.000000000', '2023-11-14T13:30:00.000000000',
       '2023-11-14T14:00:00.000000000', '2023-11-14T14:30:00.000000000',
       '2023-11-15T09:30:00.000000000', '2023-11-15T10:00:00.000000000',
       '2023-11-15T10:30:00.000000000', '2023-11-15T11:00:00.000000000',
       '2023-11-15T11:30:00.000000000', '2023-11-15T12:00:00.000000000',
       '2023-11-15T12:30:00.000000000', '2023-11-15T13:00:00.000000000',
       '2023-11-15T13:30:00.000000000', '2023-11-15T14:00:00.000000000',
       '2023-11-15T14:30:00.000000000', '2023-11-16T09:30:00.000000000',
       '2023-11-16T10:00:00.000000000', '2023-11-16T10:30:00.000000000',
       '2023-11-16T11:00:00.000000000', '2023-11-16T11:30:00.000000000',
       '2023-11-16T12:00:00.000000000', '2023-11-16T12:30:00.000000000',
       '2023-11-16T13:00:00.000000000', '2023-11-16T13:30:00.000000000',
       '2023-11-16T14:00:00.000000000', '2023-11-16T14:30:00.000000000',
       '2023-11-17T09:30:00.000000000', '2023-11-17T10:00:00.000000000',
       '2023-11-17T10:30:00.000000000', '2023-11-17T11:00:00.000000000',
       '2023-11-17T11:30:00.000000000', '2023-11-17T12:00:00.000000000',
       '2023-11-17T12:30:00.000000000', '2023-11-17T13:00:00.000000000',
       '2023-11-17T13:30:00.000000000', '2023-11-17T14:00:00.000000000',
       '2023-11-17T14:30:00.000000000', '2023-11-20T09:30:00.000000000',
       '2023-11-20T10:00:00.000000000', '2023-11-20T10:30:00.000000000',
       '2023-11-20T11:00:00.000000000', '2023-11-20T11:30:00.000000000',
       '2023-11-20T12:00:00.000000000', '2023-11-20T12:30:00.000000000',
       '2023-11-20T13:00:00.000000000', '2023-11-20T13:30:00.000000000',
       '2023-11-20T14:00:00.000000000', '2023-11-20T14:30:00.000000000',
       '2023-11-21T09:30:00.000000000', '2023-11-21T10:00:00.000000000',
       '2023-11-21T10:30:00.000000000', '2023-11-21T11:00:00.000000000',
       '2023-11-21T11:30:00.000000000', '2023-11-21T12:00:00.000000000',
       '2023-11-21T12:30:00.000000000', '2023-11-21T13:00:00.000000000',
       '2023-11-21T13:30:00.000000000', '2023-11-21T14:00:00.000000000',
       '2023-11-21T14:30:00.000000000', '2023-11-22T09:30:00.000000000',
       '2023-11-22T10:00:00.000000000', '2023-11-22T10:30:00.000000000',
       '2023-11-22T11:00:00.000000000', '2023-11-22T11:30:00.000000000',
       '2023-11-22T12:00:00.000000000', '2023-11-22T12:30:00.000000000',
       '2023-11-22T13:00:00.000000000', '2023-11-22T13:30:00.000000000',
       '2023-11-22T14:00:00.000000000', '2023-11-22T14:30:00.000000000',
       '2023-11-23T09:30:00.000000000', '2023-11-23T10:00:00.000000000',
       '2023-11-23T10:30:00.000000000', '2023-11-23T11:00:00.000000000',
       '2023-11-23T11:30:00.000000000', '2023-11-23T12:00:00.000000000',
       '2023-11-23T12:30:00.000000000', '2023-11-23T13:00:00.000000000',
       '2023-11-23T13:30:00.000000000', '2023-11-23T14:00:00.000000000',
       '2023-11-23T14:30:00.000000000', '2023-11-24T09:30:00.000000000',
       '2023-11-24T10:00:00.000000000', '2023-11-24T10:30:00.000000000',
       '2023-11-24T11:00:00.000000000', '2023-11-24T11:30:00.000000000',
       '2023-11-24T12:00:00.000000000', '2023-11-24T12:30:00.000000000',
       '2023-11-24T13:00:00.000000000', '2023-11-24T13:30:00.000000000',
       '2023-11-24T14:00:00.000000000', '2023-11-24T14:30:00.000000000',
       '2023-11-27T09:30:00.000000000', '2023-11-27T10:00:00.000000000',
       '2023-11-27T10:30:00.000000000', '2023-11-27T11:00:00.000000000',
       '2023-11-27T11:30:00.000000000', '2023-11-27T12:00:00.000000000',
       '2023-11-27T12:30:00.000000000', '2023-11-27T13:00:00.000000000',
       '2023-11-27T13:30:00.000000000', '2023-11-27T14:00:00.000000000',
       '2023-11-27T14:30:00.000000000', '2023-11-28T09:30:00.000000000',
       '2023-11-28T10:00:00.000000000', '2023-11-28T10:30:00.000000000',
       '2023-11-28T11:00:00.000000000', '2023-11-28T11:30:00.000000000',
       '2023-11-28T12:00:00.000000000', '2023-11-28T12:30:00.000000000',
       '2023-11-28T13:00:00.000000000', '2023-11-28T13:30:00.000000000',
       '2023-11-28T14:00:00.000000000', '2023-11-28T14:30:00.000000000',
       '2023-11-29T09:30:00.000000000', '2023-11-29T10:00:00.000000000',
       '2023-11-29T10:30:00.000000000', '2023-11-29T11:00:00.000000000',
       '2023-11-29T11:30:00.000000000', '2023-11-29T12:00:00.000000000',
       '2023-11-29T12:30:00.000000000', '2023-11-29T13:00:00.000000000',
       '2023-11-29T13:30:00.000000000', '2023-11-29T14:00:00.000000000',
       '2023-11-29T14:30:00.000000000', '2023-11-30T09:30:00.000000000',
       '2023-11-30T10:00:00.000000000', '2023-11-30T10:30:00.000000000',
       '2023-11-30T11:00:00.000000000', '2023-11-30T11:30:00.000000000',
       '2023-11-30T12:00:00.000000000', '2023-11-30T12:30:00.000000000',
       '2023-11-30T13:00:00.000000000', '2023-11-30T13:30:00.000000000',
       '2023-11-30T14:00:00.000000000', '2023-11-30T14:30:00.000000000',
       '2023-12-01T09:30:00.000000000', '2023-12-01T10:00:00.000000000',
       '2023-12-01T10:30:00.000000000', '2023-12-01T11:00:00.000000000',
       '2023-12-01T11:30:00.000000000', '2023-12-01T12:00:00.000000000',
       '2023-12-01T12:30:00.000000000', '2023-12-01T13:00:00.000000000',
       '2023-12-01T13:30:00.000000000', '2023-12-01T14:00:00.000000000',
       '2023-12-01T14:30:00.000000000', '2023-12-04T09:30:00.000000000',
       '2023-12-04T10:00:00.000000000', '2023-12-04T10:30:00.000000000',
       '2023-12-04T11:00:00.000000000', '2023-12-04T11:30:00.000000000',
       '2023-12-04T12:00:00.000000000', '2023-12-04T12:30:00.000000000',
       '2023-12-04T13:00:00.000000000', '2023-12-04T13:30:00.000000000',
       '2023-12-04T14:00:00.000000000', '2023-12-04T14:30:00.000000000',
       '2023-12-05T09:30:00.000000000', '2023-12-05T10:00:00.000000000',
       '2023-12-05T10:30:00.000000000', '2023-12-05T11:00:00.000000000',
       '2023-12-05T11:30:00.000000000', '2023-12-05T12:00:00.000000000',
       '2023-12-05T12:30:00.000000000', '2023-12-05T13:00:00.000000000',
       '2023-12-05T13:30:00.000000000', '2023-12-05T14:00:00.000000000',
       '2023-12-05T14:30:00.000000000', '2023-12-06T09:30:00.000000000',
       '2023-12-06T10:00:00.000000000', '2023-12-06T10:30:00.000000000',
       '2023-12-06T11:00:00.000000000', '2023-12-06T11:30:00.000000000',
       '2023-12-06T12:00:00.000000000', '2023-12-06T12:30:00.000000000',
       '2023-12-06T13:00:00.000000000', '2023-12-06T13:30:00.000000000',
       '2023-12-06T14:00:00.000000000', '2023-12-06T14:30:00.000000000',
       '2023-12-07T09:30:00.000000000', '2023-12-07T10:00:00.000000000',
       '2023-12-07T10:30:00.000000000', '2023-12-07T11:00:00.000000000',
       '2023-12-07T11:30:00.000000000', '2023-12-07T12:00:00.000000000',
       '2023-12-07T12:30:00.000000000', '2023-12-07T13:00:00.000000000',
       '2023-12-07T13:30:00.000000000', '2023-12-07T14:00:00.000000000',
       '2023-12-07T14:30:00.000000000', '2023-12-08T09:30:00.000000000',
       '2023-12-08T10:00:00.000000000', '2023-12-08T10:30:00.000000000',
       '2023-12-08T11:00:00.000000000', '2023-12-08T11:30:00.000000000',
       '2023-12-08T12:00:00.000000000', '2023-12-08T12:30:00.000000000',
       '2023-12-08T13:00:00.000000000', '2023-12-08T13:30:00.000000000',
       '2023-12-08T14:00:00.000000000', '2023-12-08T14:30:00.000000000',
       '2023-12-11T09:30:00.000000000', '2023-12-11T10:00:00.000000000',
       '2023-12-11T10:30:00.000000000', '2023-12-11T11:00:00.000000000',
       '2023-12-11T11:30:00.000000000', '2023-12-11T12:00:00.000000000',
       '2023-12-11T12:30:00.000000000', '2023-12-11T13:00:00.000000000',
       '2023-12-11T13:30:00.000000000', '2023-12-11T14:00:00.000000000',
       '2023-12-11T14:30:00.000000000', '2023-12-12T09:30:00.000000000',
       '2023-12-12T10:00:00.000000000', '2023-12-12T10:30:00.000000000',
       '2023-12-12T11:00:00.000000000', '2023-12-12T11:30:00.000000000',
       '2023-12-12T12:00:00.000000000', '2023-12-12T12:30:00.000000000',
       '2023-12-12T13:00:00.000000000', '2023-12-12T13:30:00.000000000',
       '2023-12-12T14:00:00.000000000', '2023-12-12T14:30:00.000000000',
       '2023-12-13T09:30:00.000000000', '2023-12-13T10:00:00.000000000',
       '2023-12-13T10:30:00.000000000', '2023-12-13T11:00:00.000000000',
       '2023-12-13T11:30:00.000000000', '2023-12-13T12:00:00.000000000',
       '2023-12-13T12:30:00.000000000', '2023-12-13T13:00:00.000000000',
       '2023-12-13T13:30:00.000000000', '2023-12-13T14:00:00.000000000',
       '2023-12-13T14:30:00.000000000', '2023-12-14T09:30:00.000000000',
       '2023-12-14T10:00:00.000000000', '2023-12-14T10:30:00.000000000',
       '2023-12-14T11:00:00.000000000', '2023-12-14T11:30:00.000000000',
       '2023-12-14T12:00:00.000000000', '2023-12-14T12:30:00.000000000',
       '2023-12-14T13:00:00.000000000', '2023-12-14T13:30:00.000000000',
       '2023-12-14T14:00:00.000000000', '2023-12-14T14:30:00.000000000',
       '2023-12-15T09:30:00.000000000', '2023-12-15T10:00:00.000000000',
       '2023-12-15T10:30:00.000000000', '2023-12-15T11:00:00.000000000',
       '2023-12-15T11:30:00.000000000', '2023-12-15T12:00:00.000000000',
       '2023-12-15T12:30:00.000000000', '2023-12-15T13:00:00.000000000',
       '2023-12-15T13:30:00.000000000', '2023-12-15T14:00:00.000000000',
       '2023-12-15T14:30:00.000000000', '2023-12-18T09:30:00.000000000',
       '2023-12-18T10:00:00.000000000', '2023-12-18T10:30:00.000000000',
       '2023-12-18T11:00:00.000000000', '2023-12-18T11:30:00.000000000',
       '2023-12-18T12:00:00.000000000', '2023-12-18T12:30:00.000000000',
       '2023-12-18T13:00:00.000000000', '2023-12-18T13:30:00.000000000',
       '2023-12-18T14:00:00.000000000', '2023-12-18T14:30:00.000000000',
       '2023-12-19T09:30:00.000000000', '2023-12-19T10:00:00.000000000',
       '2023-12-19T10:30:00.000000000', '2023-12-19T11:00:00.000000000',
       '2023-12-19T11:30:00.000000000', '2023-12-19T12:00:00.000000000',
       '2023-12-19T12:30:00.000000000', '2023-12-19T13:00:00.000000000',
       '2023-12-19T13:30:00.000000000', '2023-12-19T14:00:00.000000000',
       '2023-12-19T14:30:00.000000000', '2023-12-20T09:30:00.000000000',
       '2023-12-20T10:00:00.000000000', '2023-12-20T10:30:00.000000000',
       '2023-12-20T11:00:00.000000000', '2023-12-20T11:30:00.000000000',
       '2023-12-20T12:00:00.000000000', '2023-12-20T12:30:00.000000000',
       '2023-12-20T13:00:00.000000000', '2023-12-20T13:30:00.000000000',
       '2023-12-20T14:00:00.000000000', '2023-12-20T14:30:00.000000000',
       '2023-12-21T09:30:00.000000000', '2023-12-21T10:00:00.000000000',
       '2023-12-21T10:30:00.000000000', '2023-12-21T11:00:00.000000000',
       '2023-12-21T11:30:00.000000000', '2023-12-21T12:00:00.000000000',
       '2023-12-21T12:30:00.000000000', '2023-12-21T13:00:00.000000000',
       '2023-12-21T13:30:00.000000000', '2023-12-21T14:00:00.000000000',
       '2023-12-21T14:30:00.000000000', '2023-12-22T09:30:00.000000000',
       '2023-12-22T10:00:00.000000000', '2023-12-22T10:30:00.000000000',
       '2023-12-22T11:00:00.000000000', '2023-12-22T11:30:00.000000000',
       '2023-12-22T12:00:00.000000000', '2023-12-22T12:30:00.000000000',
       '2023-12-22T13:00:00.000000000', '2023-12-22T13:30:00.000000000',
       '2023-12-22T14:00:00.000000000', '2023-12-22T14:30:00.000000000',
       '2023-12-25T09:30:00.000000000', '2023-12-25T10:00:00.000000000',
       '2023-12-25T10:30:00.000000000', '2023-12-25T11:00:00.000000000',
       '2023-12-25T11:30:00.000000000', '2023-12-25T12:00:00.000000000',
       '2023-12-25T12:30:00.000000000', '2023-12-25T13:00:00.000000000',
       '2023-12-25T13:30:00.000000000', '2023-12-25T14:00:00.000000000',
       '2023-12-25T14:30:00.000000000', '2023-12-26T09:30:00.000000000',
       '2023-12-26T10:00:00.000000000', '2023-12-26T10:30:00.000000000',
       '2023-12-26T11:00:00.000000000', '2023-12-26T11:30:00.000000000',
       '2023-12-26T12:00:00.000000000', '2023-12-26T12:30:00.000000000',
       '2023-12-26T13:00:00.000000000', '2023-12-26T13:30:00.000000000',
       '2023-12-26T14:00:00.000000000', '2023-12-26T14:30:00.000000000',
       '2023-12-27T09:30:00.000000000', '2023-12-27T10:00:00.000000000',
       '2023-12-27T10:30:00.000000000', '2023-12-27T11:00:00.000000000',
       '2023-12-27T11:30:00.000000000', '2023-12-27T12:00:00.000000000',
       '2023-12-27T12:30:00.000000000', '2023-12-27T13:00:00.000000000',
       '2023-12-27T13:30:00.000000000', '2023-12-27T14:00:00.000000000',
       '2023-12-27T14:30:00.000000000', '2023-12-28T09:30:00.000000000',
       '2023-12-28T10:00:00.000000000', '2023-12-28T10:30:00.000000000',
       '2023-12-28T11:00:00.000000000', '2023-12-28T11:30:00.000000000',
       '2023-12-28T12:00:00.000000000', '2023-12-28T12:30:00.000000000',
       '2023-12-28T13:00:00.000000000', '2023-12-28T13:30:00.000000000',
       '2023-12-28T14:00:00.000000000', '2023-12-28T14:30:00.000000000'],
      dtype='datetime64[ns]')

In [106]:
times = np.sort(times)

In [107]:
#divide timestamps by 0.7:0.1:0.2, pick out the seperate points
train_num = int(len(times)*0.7)
test_num = int(len(times)*0.2)
val_num = len(times) - train_num - test_num

train_val_sep = times[train_num]
train_test_sep = times[train_num+val_num]

print(train_val_sep, train_test_sep)

2023-12-12T11:30:00.000000000 2023-12-18T13:00:00.000000000

In [100]:
times < train_val_sep

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [237]:
preds = pd.read_csv('./results/Crossformer_Stock30min_il96_ol-1_sl8_win2_fa10_dm256_nh4_el3_itr0/pred.csv')
trues = pd.read_csv('./results/Crossformer_Stock30min_il96_ol-1_sl8_win2_fa10_dm256_nh4_el3_itr0/true.csv')

In [238]:
#compute the pearson correlation coefficient row-wise
from scipy.stats import spearmanr
ICs = []
for i in range(len(preds)):
    #drop the first column, which is the timestamp
    pred = preds.iloc[i, 1:]
    true = trues.iloc[i, 1:]

    #check if there are any NaN values, if so, drop them
    if pred.isna().sum() > 0:
        pred = pred.dropna()
        true = true.dropna()
    
    #compute the correlation coefficient
    rankic = spearmanr(pred, true)[0]
    ICs.append(rankic)
ICs = np.array(ICs)

In [239]:
ICs.mean()

0.005533788940865762

In [240]:
ICs

array([ 3.03081232e-01,  2.83473389e-01,  1.93991176e-01,  2.73128371e-02,
       -1.72152964e-01, -1.39495798e-01,  1.19047619e-01, -1.43457557e-01,
        1.65546218e-01,  1.88795518e-01,  1.62464986e-01,  2.36694678e-01,
        2.24433346e-01,  1.96133378e-01,  1.97632888e-01,  1.66946779e-01,
        1.82085581e-01,  6.33053221e-02, -7.98319328e-02, -8.26388405e-03,
       -2.80131663e-04,  1.38805239e-01,  3.19327731e-02, -3.75376428e-02,
       -6.58540061e-03, -3.21731214e-01,  2.70868347e-01,  1.98039216e-01,
       -8.96358543e-02, -1.33902935e-01, -1.67787115e-01, -3.47223196e-01,
       -1.04349044e-01, -7.90469711e-02,  8.22186430e-02, -5.91077808e-02,
       -2.32492997e-02,  1.04481793e-01, -2.08712707e-02, -2.46567676e-01,
       -1.34453782e-01, -4.49579832e-01, -3.93557423e-01, -3.12605042e-01,
       -2.30252101e-01, -2.82633053e-01, -3.90476190e-01, -2.56180405e-01,
        1.68303111e-03, -4.05435712e-01, -1.36284054e-01, -1.92146052e-01,
       -2.23809524e-01, -1.73109244e-01, -1.42016807e-01, -2.24929972e-01,
       -2.17647059e-01, -2.63113863e-01, -1.82785910e-01, -5.04555134e-02,
        2.16276792e-01,  3.95518207e-01,  2.86915114e-01,  3.56682558e-01,
        2.39215686e-01,  1.08963585e-01,  7.59103641e-02,  1.20728291e-01,
        2.30532213e-01,  2.98620352e-01,  1.83473389e-01, -2.67787115e-01,
        4.95727698e-01,  2.49019608e-01,  4.52787914e-01,  3.24460646e-01,
        3.32586172e-01,  5.15830785e-01,  4.40056022e-01,  2.40616246e-01,
        3.79298271e-01,  2.54901961e-02, -2.08403361e-01, -3.47338936e-01,
        6.05084391e-02, -2.29292278e-01, -8.40571622e-02, -2.62538537e-01,
       -4.72681442e-01, -2.75229358e-01, -3.19047619e-01,  5.60224090e-03,
        2.49772604e-01])